"""ACI-RCDF 1 cubic metre of concrete mix without additives

missing!
! maximum values of coarse aggregate of any size
! granulometry limits for 3/4" coarse agg
"""
import numpy as np
from numpy import genfromtxt


def ordinary_portland(nombre_archivo, fc, granulometry_array_csv, slump=10, std=40, cement_density=3.15):
    """computes quantity of components for a cubic metre of concrete mix without additives
            according to RCDF class 1 concrete via ACI 318 absolute volumes procedure
            NO AIR INCLUDED
            returns array (weights, volumes, volumes for a 50kg sack of cement.)
    """
    revenimiento = genfromtxt('revenimientos.csv', delimiter=',')
    granulometry = genfromtxt(granulometry_array_csv, delimiter=',')
    agua_cemento = genfromtxt('water_cement.csv', delimiter=',')
    AgregadoG = genfromtxt('vol_agregado.csv', delimiter=',')
    max_size_agg = granulometry[1, 1]
    modulo_finura = granulometry[6, 2]
    peso_grava_compacto = granulometry[5, 1]
    densidad_grava = granulometry[2, 1]
    densidad_arena = granulometry[2, 2]
    humedad_grava = granulometry[7, 1]
    humedad_arena = granulometry[7, 2]
    absorcion_grava = granulometry[3, 1]
    absorcion_arena = granulometry[3, 2]
    peso_suelto_grava = granulometry[4, 1]
    peso_suelto_arena = granulometry[4, 2]
    t0 = 3.35
    fcr = max(fc - 35 + t0 * std, fc + t0 * std / np.sqrt(3))
    agua_columna = np.abs(revenimiento[1, 2:] - max_size_agg).argmin()
    agua_renglon = np.abs(revenimiento[2:5, 0:2] - slump).argmin()
    contenido_agua = revenimiento[agua_renglon, agua_columna + 2]
    aire_atrapado = revenimiento[5, agua_columna + 2]
    fr = np.flipud(agua_cemento[1:, 0])
    ac = np.flipud(agua_cemento[1:, 1])
    agua_cemento = np.interp(fcr, fr, ac)
    cemento = contenido_agua / agua_cemento
    agg_row = np.abs(AgregadoG[2:, 0] - max_size_agg).argmin()
    agg_col = np.abs(AgregadoG[1, 1:] - modulo_finura).argmin()
    grava = peso_grava_compacto * AgregadoG[agg_row + 2, agg_col + 1]
    vol_agua = contenido_agua
    vol_aire = aire_atrapado * 10
    vol_cemento = cemento / cement_density
    vol_grava = grava / densidad_grava
    vol_arena = 1000 - vol_agua - vol_cemento - vol_aire - vol_grava
    arena = densidad_arena * vol_arena
    agua_absorcion = (grava * (absorcion_grava - humedad_grava) +
                      arena * (absorcion_arena - humedad_arena)) / 100
    factor_conv = cemento / 50
    print(factor_conv)
    vol_grava2 = 1000 * grava / peso_suelto_grava
    vol_arena2 = 1000 * arena / peso_suelto_arena
    file = open(nombre_archivo + '.csv', 'w')
    file.write('Proporcionamiento' + ',1m$^3$ concreto,' + 'hidraulico $f_c$ = ' +
               str(fc) + ',kg/cm$^2$ \n')
    file.write('Material, Peso kg, Volumen l, Saco (l) \n')
    file.write('Cemento,' + str(cemento) + ',' +
               str(vol_cemento) + ',' + '50 kg \n')
    file.write('Agua,' + str(contenido_agua + agua_absorcion) + ',' + str(contenido_agua +
                                                                          agua_absorcion) + ',' + str((contenido_agua + agua_absorcion) / factor_conv) + ' \n')
    file.write('Grava,' + str(grava) + ',' + str(vol_grava2) +
               ',' + str(vol_grava2 / factor_conv) + ' \n')
    file.write('Arena,' + str(arena) + ',' + str(vol_arena2) +
               ',' + str(vol_arena2 / factor_conv) + ' \n')
    file.close()
    return fcr

Resistencias = np.array([100, 150, 200, 250, 300, 400, 420])
for resistencia in Resistencias:
    ordinary_portland('fc' + str(resistencia), resistencia, 'granulometry.csv')
# materiales = np.array(['Cemento', 'Agua', 'Grava', 'Arena'])
# texto = np.array(['Material', 'Peso 1m^3', 'Volumen 1m^3', 'Saco 50kg'])
# pesos = np.array([cemento, contenido_agua + agua_absorcion, grava, arena])
# vols = np.array([vol_cemento, contenido_agua +
#                  agua_absorcion, vol_grava2, vol_arena2])
# vols2 = np.array([50, (contenido_agua + agua_absorcion) / factor_conv,
#                   vol_grava2 / factor_conv, vol_arena2 / factor_conv])
# archivo = e
# np.savetxt(nombre_archivo + '.csv',
#            archivo,
#            fmt='%10s',             # formatting, 2 digits in this case
#            delimiter=',',          # column delimiter
#            newline='\n')           # new line character
# # footer='end of file',   # file footer
# # comments='# '          # character to use for comments
# # header='Data generated by numpy')      # file header)
